### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by mpastell** [labjack/LabJackPython#10]
Hi,
I'd be very happy to see Python 3 support.

**Comment by mnaberez** [comment]
@davelopez01 @rolsen I have been submitting pull requests with small, focused changes that I hope will be easy for you to review and merge (e.g. #37, #38, #40).  These changes are starting to fix some of the Python 3 issues without breaking the existing Python 2.5-2.7 support.  Since 899470c0ac7e5afb100afc050585816d2a54ae76, `setup.py` will refuse to install on versions that aren't officially supported (including Python 3).  This will allow incremental work to be done and released without any change to your supported version policy.

**Comment by danwoodard** [comment]
Can LJM be extended to support the U6?

**Comment by rolsen** [comment]
@danwoodard, no, LJM cannot be extended to support the U6, as much as we'd like to. The APIs of LJM and the U6 are not compatible.

**Comment by k7hoven** [comment]
The scientific community has been fast in switching to Python 3. For us, the only reason left for using Python 3 and 2 in parallel is LabJack. How about official support?

**Comment by davelopez01** [comment]
At this time, there are still no plans to add official Python 3 support to LabJackPython. LabJackPython is for the LabJack U12, U3, U6 and UE9.

For the LabJack T7, Digit and upcoming devices there is the [LJM Python](http://labjack.com/support/ljm/examples/python) interface which does support Python 3.

**Comment by davelopez01** [comment]
To update, we (LabJack) changed our plans and are now adding official Python 3 support to LabJackPython. There is no time frame on completion, but I have started pushing updates to the repository.

**Comment by shraken** [comment]
any update on official python3 support?  sultanqasim fork works on my mac osx and raspberry pi systems but is 220 commits behind labjack master at this point.

**Comment by davelopez01** [comment]
A lot of functionality has been updated, but we have yet to do a finalized test for Python 3 compatibility, a couple of examples still need to be updated and we are considering some additional changes I mention here:

https://github.com/labjack/LabJackPython/issues/93

Python 3 development has been delayed recently as we are working on a new LabJack product release.

Try the current development version here on GitHub and let us know if you run into any issues.

**Comment by ygaudet** [comment]
All, I'm running into a problem, in Python3 using a single counter for a Flowmeter. 
When reading the counter using d.getFeedback(u3.Counter0(Reset = False)) from the u3.py documented example. 
We get a TypeError: a bytes-like object is required, not 'str' from return unpack('<I', inStr)[0]
at line 2784 of u3.py
I tried to help the unpacking by using return unpack('<I', bytes(inStr, 'utf8') )[0] but that then fails randomly with struct.error: unpack requires a bytes object of length 4.
For what ever reason sometime the bytes(inStr, 'utf8') as a len of 5?
Any idea would help.

**Comment by davelopez01** [comment]
@ygaudet I pushed some Feedback Counter changes to fix the Python 3 error. I didn't see any issues with the Counter value being 5-bytes. Let me know if you run into further issues.
