### ISSUE TITLE
reading zero values

### ISSUE THREAD

**Issue by bje-** [labjack/LabJackPython#101]
I have some code that reads from an analogue pin (p) using the following code:

        if isinstance(unit, U6):
            reading = unit.getAIN(p)
        elif isinstance(unit, U12):
            reading = unit.eAnalogIn(p)['voltage']

For extended periods, these two read functions were returning 0V when non-zero voltage sources were connected to a U6 and a U12.  Is this a known problem in the exodriver or in the Python library?  It has magically come good again without (as far as I know) doing anything. Grateful for ideas on how to track down the problem!

**Comment by davelopez01** [comment]
There isn't a known problem in LabJackPython or Exodriver like you are describing. To troubleshoot:

- How are you error checking the code you provided? Just making sure that "reading" isn't defaulted to zero before your calls, an exception occurs and you are seeing the default "reading" voltage you set. Make sure exceptions are handled and you check what error you are getting.

- What do you have connected to your U6 or U12? Do you get 0 volts with a certain signal, or is your computer sleeping when the 0 volts occurs?

- What operating system are you running?

- If you connect to a different USB port, does it help the issue?

**Comment by bje-** [comment]
Thanks, a few good suggestions. I will come back with more info soon.

**Comment by bje-** [comment]
BTW we are running on CentOS Linux. The U6 and U12s are connected to isolators which indicate battery voltages in the range of 0-5V and should never be zero.

**Comment by bje-** [comment]
I found it was our code setting the reading to 0, sorry!
