### ISSUE TITLE
NullHandleException() condition: None < int is syntax error

### ISSUE THREAD

**Issue by brianmapes** [labjack/LabJackPython#103]
May I recommend: 
	if (handle or -999) <= 0:
            raise NullHandleException()

 Instead of: 
	if handle <= 0:
            raise NullHandleException()
 
in LabJackPython.py. (Now, why is my handle null? One issue at a time... :)

**Comment by davelopez01** [comment]
On Mac and Linux, a handle of NULL indicates the device was not found. this is based on the LJUSB_OpenDevice functionality. I can look into this further in a couple of days

**Comment by brianmapes** [comment]
I’m beyond it, by rebooting.

 But for the future, better if someone gets a device not found rather than a syntax error. It’s a python 2->3 fix I think.

Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Feb 10, 2018, at 4:15 PM, David Lopez <notifications@github.com<mailto:notifications@github.com>> wrote:


On Mac and Linux, a handle of NULL indicates the device was not found. this is based on the LJUSB_OpenDevice functionality. I can look into this further in a couple of days
