### ISSUE TITLE
No examples for U12?

### ISSUE THREAD

**Issue by brianmapes** [labjack/LabJackPython#104]
I am preparing an undergrad lab, we want a time series of temperature from the probe, maybe a few samples per second.  

I have a U12, installed the driver and Python, it is ready to use in a Jupyter notebook!  This seems to work: 
d = u12.U12(debug=True) # create a u12 device controller

Now what? I cannot seem to find any example codes. This only has u3, u6, u9. 
https://github.com/labjack/LabJackPython/blob/master/Examples/streamTest.py
The u9 functions used in it do not exist in u12. 

Presumably I want AIstreamstart - AIstreamread -- AI streamclose. (What does AI stand for? or do I want raw?)

What are the asterisks by some in/out variables in the reference manual --
https://labjack.com/support/datasheets/u12/programming-reference/aistreamstart? 

The docstring on aiStreamStart suggests this usage: 
>>> dev = U12()
>>> dev.aiStreamStart(1, [0], 200)
{'scanRate': 200.0, 'idnum': 1}
File:      //anaconda/envs/ATMOcanes/lib/python3.6/site-packages/u12.py
Type:      method

But when I literally type this, it fails with botu u12 and U12 (capital) 
NameError                                 Traceback (most recent call last)
<ipython-input-28-2d6356230344> in <module>()
----> 1 dev = U12()
      2 dev.aiStreamStart(1, [0], 200)

NameError: name 'U12' is not defined

**Comment by brianmapes** [comment]
when I call aiStreamStart(1, [0], 200) as a method of my d object, I get this incomprehensible (to me) error: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-031973dda83c> in <module>()
----> 1 d.aiStreamStart(1, [0], 200)

...
//anaconda/envs/ATMOcanes/lib/python3.6/ctypes/__init__.py in __getitem__(self, name_or_ordinal)
    364 
    365     def __getitem__(self, name_or_ordinal):
--> 366         func = self._FuncPtr((name_or_ordinal, self))
    367         if not isinstance(name_or_ordinal, int):
    368             func.__name__ = name_or_ordinal

AttributeError: dlsym(0x7fc937eca220, AIStreamStart): symbol not found

**Comment by davelopez01** [comment]
I recommend using the eAnalogIn method instead. Execution time is around 20 ms, it is easier to use, and will fit your few samples per second requirement. Example code is in the source docstring, which can also be displayed with the Python help method:

import u12
help(u12.U12.eAnalogIn)

Regarding the U12 stream functions, they are for sampling at faster rates such as 200 to 1200 samples per second. AI stands for analog input. The aiStreamStart example code in the docstring doesn't look clear enough. It should be something like:

import u12
dev = u12.U12()
dev.aiStreamStart(1, [0], 200)

u12 is the module and U12 is the class. Alternatively it could of had a "from u12 import U12" before the calls for them to be correct.

Regardng asterisks, our general documentation is based on the C/C++ header file. In C/C++, an asterisk indicates the parameter is a pointer (array or pass by reference).

"symbol not found" indicates a function from a library can't be found. On Linux and Mac, the u12 module only uses the Exodriver which does not have the AIStreamStart function. Currently that function is only available on Windows where the u12 module uses the ljackuw (UW) library. Let me know if you need the stream functions for Linux or Mac OS X and I can look into it further.

**Comment by brianmapes** [comment]
David, Thanks!
Quite adequate for our simple case.

https://github.com/ATMOcanes/ATM303/blob/master/notebooks/LabJack_sampler_and_plotter.ipynb


Brian Mapes


On Feb 10, 2018, at 5:05 PM, David Lopez <notifications@github.com<mailto:notifications@github.com>> wrote:


I recommend using the eAnalogIn method instead. Execution time is around 20 ms, it is easier to use, and will fit your few samples per second requirement. Example code is in the source docstring, which can also be displayed with the Python help method:

import u12
help(u12.U12.eAnalogIn)

Regarding the U12 stream functions, they are for sampling at faster rates such as 200 to 1200 samples per second. AI stands for analog input. The aiStreamStart example code in the docstring doesn't look clear enough. It should be something like:

import u12
dev = u12.U12()
dev.aiStreamStart(1, [0], 200)

u12 is the module and U12 is the class. Alternatively it could of had a "from u12 import U12" before the calls for them to be correct.

Regardng asterisks, our general documentation is based on the C/C++ header file. In C/C++, an asterisk indicates the parameter is a pointer (array or pass by reference).

"symbol not found" indicates a function from a library can't be found. On Linux and Mac, the u12 module only uses the Exodriver which does not have the AIStreamStart function. Currently that function is only available on Windows where the u12 module uses the ljackuw (UW) library. Let me know if you need the stream functions for Linux or Mac OS X and I can look into it further.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flabjack%2FLabJackPython%2Fissues%2F104%23issuecomment-364698788&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7Ca7a0f5d8c2b3490d7e9808d570d26169%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636538971252767699&sdata=uvKEnz5JshtcD06ig9lRBTx8R51d04dxhAToiIixhII%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB_VQsDL1ryzulpQLUFEQ3UDIOOANtsvks5tThKhgaJpZM4SBA9A&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7Ca7a0f5d8c2b3490d7e9808d570d26169%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636538971252767699&sdata=9k86MbzGOI%2FMvTPeTFayA8%2BE2w%2FwFJfeKhQ0hAriDX0%3D&reserved=0>.

*********************************************
Brian Mapes, Professor
Department of Atmospheric Sciences
Meteorology and Physical Oceanography Program
RSMAS, University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149-1098

phone: (305) 421-4275
fax: (305) 421-4696
email: mapes@miami.edu<mailto:mapes@miami.edu>
Web: http://www.rsmas.miami.edu/users/bmapes/
**********************************************
