### ISSUE TITLE
close() method does not release the device on Windows 10

### ISSUE THREAD

**Issue by EduardoNigro** [labjack/LabJackPython#118]
When executing the basic U3 example code, the final command does not really release the U3 device for  other applications to use it. More specifically, if a try to open the same device from MATLAB, I get the following error: **_LabJack is already open via USB in another program or process_**.
``` python 
import u3
d = u3.U3()
d.configU3()
d.close()
```

**Comment by EduardoNigro** [comment]
By the way, after digging through my old MATLAB implementation using the LabJackUD C library, I found a workaround as shown in the simple class below:

```python
from u3 import U3
from LabJackPython import LabJackException, _loadLibrary


class LabJackU3:
    def __init__(self, serialnum=None):
        """
        Class constructor
        """
        self._staticlib = _loadLibrary()
        self._commhandle = None
        # Attempting to open the device
        try:
            if serialnum:
                # Opens LabJack with specific serial number
                self.serialnum = serialnum
                self._commhandle = U3(autoOpen = False)
                self._commhandle.open(serial=serialnum)
            else:
                # Opens first available LabJack
                self._commhandle = U3(autoOpen = False)
                self._commhandle.open()
                self.serialnum = self._commhandle.configU3()['SerialNumber']
        except LabJackException as error:
            print(error)
        else:
            print('Opened LabJack : ' + str(self.serialnum))

    def close(self):
        self._staticlib.Close(self._commhandle.handle)
        print('Closed LabJack : ' + str(self.serialnum))
```

**Comment by sjarman28** [comment]
Apologies for the delayed response. Note that the UD library close function is already defined as a part of LabJackPython.py. There are no parameters to the function:
https://github.com/labjack/LabJackPython/blob/36677a1a5a09cdb11b589af2d1366dbbd64ff9d3/src/LabJackPython.py#L2804-L2819

Your workaround is sufficient for a single device setup, but the UD library Close function will close the connections to every connected UD device; it would not work in a multi-device setup where you only want to close one device connection. This is a limitation of the UD library. As a result, we cannot add in the UD library Close function as part of the device close method without breaking backwards compatibility and allowing behavior that should be outside of the scope of the device class.

We decided to leave the implementation as it is and change the documentation to clarify that the device close function does not close the connection on Windows. With this, the only way to close device connections on Windows is by calling the UD library Close function. Additionally, ending the process will automatically close the connections.
