### ISSUE TITLE
open source liblabjackusb.so

### ISSUE THREAD

**Issue by raveslave** [labjack/LabJackPython#131]
is it possible to get the source for liblabjackusb.so? or a pure python implementation?

**Comment by raveslave** [comment]
ping

**Comment by LabJackAdmin** [comment]
Hello, the source code is available through our exodriver project:
https://github.com/labjack/exodriver

**Comment by raveslave** [comment]
oups, didn't know, that is perfect!
curious if anyone ever ported that driver/protocol to python?

**Comment by LabJackAdmin** [comment]
This is the low level USB layer for our U series devices, there is no low level replacement in python.
