### ISSUE TITLE
writeAesStingRegisterRequest() uses undefined name TCP_HEADER

### ISSUE THREAD

**Issue by mnaberez** [labjack/LabJackPython#21]
In [LabJackPython/Modbus.py line 208](https://github.com/labjack/LabJackPython/blob/cf7cc2cce9c16dda07e4ed630d2fe69a090a4d60/src/Modbus.py#L208), the name `TCP_HEADER` is undefined.

**Comment by davelopez01** [comment]
It looks like TCP_HEADER should be _buildHeaderBytes(). TCP_HEADER was removed in this [commit](https://github.com/labjack/LabJackPython/commit/438c9d8daae27f0a66991b7d59cf83e9f69647e1) and it seems like writeAesStingRegisterRequest's usage of it was missed. Next week I'll look into fixing this and your pull requests.

**Comment by davelopez01** [comment]
Resolved in this [commit](https://github.com/labjack/LabJackPython/commit/f681f6b6e224e7c552ca1137439cc23e1ee8901d). The writeAesStingRegisterRequest function has been removed from Modbus.py.
