### ISSUE TITLE
_openWirelessBridgeOnWindows() uses undefined names deviceType and handleOnly

### ISSUE THREAD

**Issue by mnaberez** [labjack/LabJackPython#31]
In [LabJackPython.py on lines 1419-1459](https://github.com/labjack/LabJackPython/blob/cf7cc2cce9c16dda07e4ed630d2fe69a090a4d60/src/LabJackPython.py#L1419-L1459), the function `_openWirelessBridgeOnWindows()` uses the undefined names `deviceType` and `handleOnly`.  It also uses the undefined name `LabjackException`, which is fixed in PR #25.

**Comment by davelopez01** [comment]
Resolved in this [commit](https://github.com/labjack/LabJackPython/commit/48a9db5714d089bf2bd2ea808e8894734bc70fc9). I removed the section of code, which was unreachable, that used deviceType and handleOnly.
