### ISSUE TITLE
i2c response handling differs on u6.py only

### ISSUE THREAD

**Issue by mnaberez** [labjack/LabJackPython#34]
The `i2c()` function in u6.py [assigns to `oddResponse`](https://github.com/labjack/LabJackPython/blob/3a02019d8909819295ca54626694d6c4f0847f5e/src/u6.py#L1006-L1016) but never uses it.  However, both u3.py and ue9.py use `oddResponse` and it [affects the return value](https://github.com/labjack/LabJackPython/blob/3a02019d8909819295ca54626694d6c4f0847f5e/src/u3.py#L1471-L1484).

u6.py should be either be changed to work like u3.py and ue9.py, or the `oddResponse` variable should be removed from it.

**Comment by davelopez01** [comment]
I resolved the issue in this [commit]:(https://github.com/labjack/LabJackPython/commit/08ccc72a7ffe789c74e8868360ed67c91bcdfa72). The i2c method in u6.py now returns the I2CBytes list the same way as u3.py and ue9.py when NumI2CBytesToReceive is odd.
