### ISSUE TITLE
UE9.streamData() uses undefined name retResult

### ISSUE THREAD

**Issue by mnaberez** [labjack/LabJackPython#58]
[`retResult` is used in `streamData()`](https://github.com/labjack/LabJackPython/blob/987ac0959d0dcd56501ec90e56cb28db1a1ecb15/src/ue9.py#L1142) but this name is never defined.

**Comment by davelopez01** [comment]
Fixed in this [commit](https://github.com/labjack/LabJackPython/commit/aaf3a81471b21882d30df324ad5dfaf10625a1ba).
