### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by allisontsay** [labjack/LabJackPython#89]
This worked the first time I  ran it, but now, I keep getting  IndexError: list index out of range?

**Comment by mnaberez** [comment]
Could you please post the full backtrace?  There are a huge number of places where an `IndexError` could potentially occur (e.g. anytime a `list` is accessed).  Without knowing the file and line number that this occurred in, there's no way to troubleshoot it.

**Comment by isaac-ped** [comment]
I am getting the same error if I try to initialize a connection without unplugging the device and plugging it back in again. It does not seem to disconnect from the LabJack device until I unplug it.

The easiest way for me to get this error is with the LabJackPython.listAll() command. When I try to list all connected devices twice in a row, it gives me the same error:

>>> import LabJackPython
>>> LabJackPython.listAll(3)
{'320065320': {'deviceName': 'U3-LV', 'streamStarted': False, 'streamConfiged': False, 'handle': None, 'localId': 1, 'serialNumber': 320065320, '_autoCloseSetup': False, 'deviceLock': <thread.lock object at 0x1044d1990>, 'devType': 3, 'hardwareVersion': '1.30', 'versionInfo': 2, 'bootloaderVersion': '0.27', 'changed': {'deviceName': 'U3-LV', 'hardwareVersion': '1.30', 'localId': 1, 'serialNumber': 320065320, 'bootloaderVersion': '0.27', 'versionInfo': 2, 'ipAddress': '', 'firmwareVersion': '1.46'}, 'debug': False, 'streamPacketOffset': 0, 'ipAddress': '', 'firmwareVersion': '1.46', 'modbusPrependZeros': True}}
>>> LabJackPython.listAll(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "LabJackPython.py", line 1194, in listAll
    return __listAllU3Unix()
  File "LabJackPython.py", line 2767, in __listAllU3Unix
    device = openLabJack(LJ_dtU3, 1, firstFound = False, devNumber = i+1)
  File "LabJackPython.py", line 1479, in openLabJack
    return _makeDeviceFromHandle(handle, deviceType)
  File "LabJackPython.py", line 1540, in _makeDeviceFromHandle
    device.localId = rcvDataBuff[21] & 0xff
IndexError: list index out of range

**Comment by davelopez01** [comment]
The index out of range error is due to there being an incomplete or no response packet from the U3.

Are you using Mac OS X 10.11, El Capitan? If so, update to the latest version of El Capitan (10.11.4 or newer) and that should help. There was an OS X bug that was causing communication issues after opening a LabJack device over USB more than once, and the recent update fixed that.

If that doesn't help, what operating system are you using? What version of Python are you using?

**Comment by isaac-ped** [comment]
Ahh, excellent! I upgraded to 10.11.4, and it all seems to work now. Thanks so much!
