### ISSUE TITLE
Unable to find "labjackud" when running from Cygwin

### ISSUE THREAD

**Issue by sayo9394** [labjack/LabJackPython#96]
After installing Labjack U3 windows drivers, and installing LabJackPython (master) on Cygwin (Python 2.7.13), it failed to load the driver when importing u3, prompting that the file was not found. 

I managed to fix the issue by adding changing LabJackPython.py, line 135 from;

    wlib = ctypes.CDLL("labjackud") 

to

    wlib = ctypes.CDLL("labjackud.dll")

**Comment by davelopez01** [comment]
Thanks for making us aware of this. I made a commit with this change. It looks like something changed in Cygwin or Python, and specifying labjackud.dll is now needed.
