### ISSUE TITLE
SIGALRM in outputSinDac.py not found

### ISSUE THREAD

**Issue by vogt31337** [labjack/LabJackPython#98]
outputSinDac.py, line 87 in <module>
 signal.signal(signal.SIGALRM, dacs.handleSetDac) 
AttributeError: 'module' object has no attribute 'SIGALRM'

Windows 7
Python 2.7.13
installed via pip install.

**Comment by davelopez01** [comment]
Thanks for mentioning this. Currently this example is only Linux and Mac compatible. I haven't gotten around to updating it for Windows yet, but I'll look into it soon.

**Comment by mnaberez** [comment]
We should probably add something like this until it's updated:
```
import os
assert os.name == "posix", "This example makes Unix-specific assumptions"
```
That error will be clearer to Windows users than the `AttributeError` they currently get.

**Comment by davelopez01** [comment]
@mnaberez , thanks. If I can't get to updating this example for cross-platform support by Friday (06/23), I'll probably add your assert code for the meantime.

**Comment by davelopez01** [comment]
Resolved in latest commit. The new outputSinDac works on Windows, Linux and Mac. The old, Unix only example is now called outputSinDacUnix.
